---
title: "Development"
author: "randy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# knitr::opts_chunk(echo = TRUE)

## clean the R environment
rm(list = ls())
freshr::freshr()

## load packages
library(here)
library(tidyverse)
library(testthat)
library(usethis)
library(devtools)

load_all()

# ?testthat::test_file
# ?devtools::test
# path <- testthat_example("success")
# test_file(path)
# test_file(path, reporter = "minimal")

## check the directory for the file
here::dr_here()
here::set_here()
```

```{r}
## check the package version activPAL
packageVersion("activPAL")

## look at the files in the same directory
here::here() %>%
  list.files()
```



```{r}
use_package("R", type = "Depends", min_version = "4.1")
use_package("dplyr", type = "Depends", min_version = "1.1.1")
use_package("ggplot2", type = "Depends", min_version = "3.4.2")
use_package("readr", type = "Depends", min_version = "2.1.4")
```


```{r}
## document the description
document()
## always check 
## it's good to establish the habit of checking this often.
# check()
```


```{r}
build_readme()

usethis::use_roxygen_md()
document()

devtools::check()
```



